Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Redis 连接失败: module 'django.core.cache.backends.redis' has no attribute 'Redis'
堆栈信息:
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 76, in verification
    r = redis.Redis(
        ^^^^^^^^^^^
AttributeError: module 'django.core.cache.backends.redis' has no attribute 'Redis'

"POST /verification/ HTTP/1.1" 200 129
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Redis 连接失败: Authentication required.
堆栈信息:
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 87, in verification
    ping_response = r.ping()
                    ^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\commands\core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 1530, in get_connection
    connection.connect()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 397, in connect_check_health
    self.on_connect_check_health(check_health=check_health)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 517, in on_connect_check_health
    self.read_response()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 644, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 38, in _read_response
    raise error
redis.exceptions.AuthenticationError: Authentication required.

"POST /verification/ HTTP/1.1" 200 129
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
Redis 连接失败: invalid password
堆栈信息:
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 87, in verification
    ping_response = r.ping()
                    ^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\commands\core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 1530, in get_connection
    connection.connect()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 397, in connect_check_health
    self.on_connect_check_health(check_health=check_health)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 469, in on_connect_check_health
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\connection.py", line 644, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\redis\_parsers\resp2.py", line 38, in _read_response
    raise error
redis.exceptions.AuthenticationError: invalid password

"POST /verification/ HTTP/1.1" 200 129
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 304 0
"POST /verification/ HTTP/1.1" 200 57
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 57
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 111
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 57
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 17
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\parsers.py", line 66, in parse
    return json.load(decoded_stream, parse_constant=parse_constant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\utils\json.py", line 31, in load
    return json.load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 354, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 1 (char 30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 153, in register
    email = request.data.get('email')
            ^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\request.py", line 221, in data
    self._load_data_and_files()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\request.py", line 284, in _load_data_and_files
    self._data, self._files = self._parse()
                              ^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\request.py", line 359, in _parse
    parsed = parser.parse(stream, media_type, self.parser_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\parsers.py", line 68, in parse
    raise ParseError('JSON parse error - %s' % str(exc))
rest_framework.exceptions.ParseError: JSON parse error - Expecting ',' delimiter: line 3 column 1 (char 30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 209, in register
    print(e.message)
          ^^^^^^^^^
AttributeError: 'ParseError' object has no attribute 'message'
"POST /register/ HTTP/1.1" 500 156713
"POST /verification/ HTTP/1.1" 200 17
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1364, "Field 'username' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 200, in register
    user.save()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\base.py", line 902, in save
    self.save_base(
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\base.py", line 1008, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\base.py", line 1169, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\base.py", line 1210, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1868, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1882, in execute_sql
    cursor.execute(sql, params)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 825, in _read_query_result
    result.read()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1364, "Field 'username' doesn't have a default value")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 209, in register
    print(e.message)
          ^^^^^^^^^
AttributeError: 'OperationalError' object has no attribute 'message'
"POST /register/ HTTP/1.1" 500 263435
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Not Found: /varification/
"GET /varification/ HTTP/1.1" 404 2682
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 17
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /register/ HTTP/1.1" 200 30
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Not Found: /varification/
"GET /varification/ HTTP/1.1" 404 2682
Method Not Allowed: /login/
"GET /login/ HTTP/1.1" 405 5524
"POST /login/ HTTP/1.1" 200 5492
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 5492
"POST /verification/ HTTP/1.1" 200 17
Not Found: /regist/
"POST /regist/ HTTP/1.1" 404 2665
Internal Server Error: /register/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'NoneType'>`
"POST /register/ HTTP/1.1" 500 89000
"POST /register/ HTTP/1.1" 200 34
"POST /login/ HTTP/1.1" 200 27
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 17
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
"POST /verification/ HTTP/1.1" 200 17
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 34
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 69
Method Not Allowed: /verification/
"GET /verification/ HTTP/1.1" 405 5587
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 30
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 30
"POST /register/ HTTP/1.1" 200 34
"POST /verification/ HTTP/1.1" 200 17
"POST /verification/ HTTP/1.1" 200 57
"POST /verification/ HTTP/1.1" 200 17
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 30
"POST /register/ HTTP/1.1" 200 34
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 34
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 30
"POST /register/ HTTP/1.1" 200 63
"POST /register/ HTTP/1.1" 200 63
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 34
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /verification/ HTTP/1.1" 200 17
"POST /register/ HTTP/1.1" 200 69
"POST /register/ HTTP/1.1" 200 56
"POST /register/ HTTP/1.1" 200 63
"POST /login/ HTTP/1.1" 200 29
"POST /login/ HTTP/1.1" 200 29
"POST /login/ HTTP/1.1" 200 33
"POST /login/ HTTP/1.1" 200 31
"POST /login/ HTTP/1.1" 200 31
"POST /login/ HTTP/1.1" 200 33
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 31, in login
    user = User.objects.get(email=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
MarkFlowImpl.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 35, in login
    user = User.objects.get(id=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '\\n'.
"POST /login/ HTTP/1.1" 500 186224
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 31, in login
    user = User.objects.get(email=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
MarkFlowImpl.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 35, in login
    user = User.objects.get(id=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '\\n'.
"POST /login/ HTTP/1.1" 500 186224
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 31, in login
    user = User.objects.get(email=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
MarkFlowImpl.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '\\t'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 35, in login
    user = User.objects.get(id=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '\\t'.
"POST /login/ HTTP/1.1" 500 186224
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 31, in login
    user = User.objects.get(email=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
MarkFlowImpl.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: "1' OR '1' = '1"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 35, in login
    user = User.objects.get(id=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got "1' OR '1' = '1".
"POST /login/ HTTP/1.1" 500 187166
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /register/ HTTP/1.1" 200 69
Method Not Allowed: /register/
"GET /register/ HTTP/1.1" 405 5551
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 22, in login
    account = request.data.get('account')
              ^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'get'
"POST /login/ HTTP/1.1" 500 108377
"POST /login/ HTTP/1.1" 200 33
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 31, in login
    user = User.objects.get(email=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
MarkFlowImpl.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2128, in get_prep_value
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: "1' OR '1' = '1"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py", line 35, in login
    user = User.objects.get(id=account)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 619, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1588, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1415, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 38, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 410, in get_prep_lookup
    return super().get_prep_lookup()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\lookups.py", line 96, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\fields\__init__.py", line 2130, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got "1' OR '1' = '1".
"POST /login/ HTTP/1.1" 500 187172
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /test3.html/test3.html
"GET /test3.html/test3.html HTTP/1.1" 404 2697
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2667
Method Not Allowed: /login/
"GET /login/ HTTP/1.1" 405 5524
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /login HTTP/1.1" 301 0
Method Not Allowed: /login/
"GET /login/ HTTP/1.1" 405 5524
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2676
Bad Request: /login/
"POST /login/ HTTP/1.1" 400 5541
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /WordsSearchRequest/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\WordAddView.py", line 27, in get
    data = request.data.get('words')
           ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'
"GET /WordsSearchRequest/ HTTP/1.1" 500 85797
Internal Server Error: /WordsSearchRequest/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\WordAddView.py", line 27, in get
    data = request.data.get('words')
           ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'
"GET /WordsSearchRequest/ HTTP/1.1" 500 85934
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\WordAddView.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /WordsSearchRequest/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\WordAddView.py", line 28, in get
    data = request.data.get('words')
           ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'
"GET /WordsSearchRequest/ HTTP/1.1" 500 85934
Watching for file changes with StatReloader
Internal Server Error: /WordsSearchRequest/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 144, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\WordAddView.py", line 27, in get
    data = request.data.get('words')
           ^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'
"GET /WordsSearchRequest/ HTTP/1.1" 500 85934
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /WordsSearchRequest/
"GET /WordsSearchRequest/ HTTP/1.1" 404 2862
Method Not Allowed: /wordsSearchRequest/
"GET /wordsSearchRequest/ HTTP/1.1" 405 5636
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2838
Internal Server Error: /wordsSearchRequest/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: word_search() missing 1 required positional argument: 'request'
"POST /wordsSearchRequest/ HTTP/1.1" 500 105613
Watching for file changes with StatReloader
Method Not Allowed: /wordsSearchRequest/
"GET /wordsSearchRequest/ HTTP/1.1" 405 5636
Bad Request: /wordsSearchRequest/
"POST /wordsSearchRequest/ HTTP/1.1" 400 5655
"GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 200 540434
Bad Request: /wordsSearchRequest/
"POST /wordsSearchRequest/ HTTP/1.1" 400 5655
Bad Request: /wordsSearchRequest/
"POST /wordsSearchRequest/ HTTP/1.1" 400 5655
Watching for file changes with StatReloader
"POST /wordsSearchRequest/ HTTP/1.1" 200 5708
Watching for file changes with StatReloader
"POST /wordsSearchRequest/ HTTP/1.1" 200 5624
"POST /wordsSearchRequest/ HTTP/1.1" 200 5624
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /wordsSearchRequest/ HTTP/1.1" 200 5624
"POST /wordsSearchRequest/ HTTP/1.1" 200 6540
"POST /wordsSearchRequest/ HTTP/1.1" 200 7106
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
"POST /wordsSearchRequest/ HTTP/1.1" 200 7106
"POST /wordsSearchRequest/ HTTP/1.1" 200 7107
"POST /wordsSearchRequest/ HTTP/1.1" 200 7105
Watching for file changes with StatReloader
"POST /wordsSearchRequest/ HTTP/1.1" 200 7107
"POST /wordsSearchRequest/ HTTP/1.1" 200 7105
"POST /wordsSearchRequest/ HTTP/1.1" 200 7087
"POST /wordsSearchRequest/ HTTP/1.1" 200 7087
"POST /wordsSearchRequest/ HTTP/1.1" 200 7556
"POST /wordsSearchRequest/ HTTP/1.1" 200 7556
"POST /wordsSearchRequest/ HTTP/1.1" 200 5624
"POST /wordsSearchRequest/ HTTP/1.1" 200 7254
Not Found: /
"GET / HTTP/1.1" 404 2787
Not Found: /
"GET / HTTP/1.1" 404 2787
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py", line 23, in login
    account = request.data.word_search('account')
              ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'word_search'
"POST /login/ HTTP/1.1" 500 106363
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 33
"POST /login/ HTTP/1.1" 200 33
Not Found: /words/search
"POST /words/search HTTP/1.1" 404 2842
Not Found: /words/search
"POST /words/search HTTP/1.1" 404 2842
Not Found: /words/search
"POST /words/search HTTP/1.1" 404 2842
Watching for file changes with StatReloader
Internal Server Error: /words/search
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\utils\deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 6961b4cb.r20.cpolar.top/words/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /words/search HTTP/1.1" 500 79798
Internal Server Error: /words/search
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\utils\deprecation.py", line 122, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 6961b4cb.r20.cpolar.top/words/search/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
"POST /words/search HTTP/1.1" 500 79798
"POST /login/ HTTP/1.1" 200 33
"POST /words/search/ HTTP/1.1" 200 702
"POST /words/search/ HTTP/1.1" 200 702
"POST /login/ HTTP/1.1" 200 33
"POST /words/search/ HTTP/1.1" 200 702
"POST /login/ HTTP/1.1" 200 33
"POST /words/search/ HTTP/1.1" 200 702
"POST /login/ HTTP/1.1" 200 33
"POST /words/search/ HTTP/1.1" 200 702
Not Found: /
"GET / HTTP/1.1" 404 2781
Not Found: /
"GET / HTTP/1.1" 404 2781
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /words/search/
"GET /words/search/ HTTP/1.1" 405 5582
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2832
"POST /words/search/ HTTP/1.1" 200 7532
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7230
"POST /words/search/ HTTP/1.1" 200 7230
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7230
"POST /words/search/ HTTP/1.1" 200 7230
"POST /words/search/ HTTP/1.1" 200 7230
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\get_word_analysis.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\import_words_to_db.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7230
"POST /words/search/ HTTP/1.1" 200 6867
"POST /words/search/ HTTP/1.1" 200 6342
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\import_words_to_db.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 6342
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\import_words_to_db.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\import_words_to_db.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\import_words_to_db.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7230
"POST /words/search/ HTTP/1.1" 200 6838
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 6838
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 6838
"POST /words/search/ HTTP/1.1" 200 6050
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7613
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5599
"POST /words/search/ HTTP/1.1" 200 7613
"POST /words/search/ HTTP/1.1" 200 5599
"POST /words/search/ HTTP/1.1" 200 5599
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7147
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /words/search/
"GET /words/search/ HTTP/1.1" 405 5582
"POST /words/search/ HTTP/1.1" 200 6653
"POST /words/search/ HTTP/1.1" 200 7117
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5600
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7332
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 382
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 382
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 399
"POST /words/search/ HTTP/1.1" 200 7133
"POST /words/search/ HTTP/1.1" 200 7142
"POST /words/search/ HTTP/1.1" 200 7421
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 7153
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 7435
"POST /words/search/ HTTP/1.1" 200 49
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 7145
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 49
"POST /words/search/ HTTP/1.1" 200 5582
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5582
"POST /words/search/ HTTP/1.1" 200 49
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\spell_checker.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5582
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 5872
"POST /words/search/ HTTP/1.1" 200 7599
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 133
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 141
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5958
"POST /words/search/ HTTP/1.1" 200 202
"POST /words/search/ HTTP/1.1" 200 5607
"POST /words/search/ HTTP/1.1" 200 201
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 5958
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 219
"POST /words/search/ HTTP/1.1" 200 5550
"POST /words/search/ HTTP/1.1" 200 5600
"POST /words/search/ HTTP/1.1" 200 231
"POST /words/search/ HTTP/1.1" 200 5938
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 197
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 222
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 5958
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 222
"POST /words/search/ HTTP/1.1" 200 243
"POST /words/search/ HTTP/1.1" 200 214
"POST /words/search/ HTTP/1.1" 200 112
"POST /words/search/ HTTP/1.1" 200 116
"POST /words/search/ HTTP/1.1" 200 201
"POST /words/search/ HTTP/1.1" 200 201
"POST /words/search/ HTTP/1.1" 200 201
Watching for file changes with StatReloader
Not Found: /word/search/
"GET /word/search/ HTTP/1.1" 404 2835
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2832
Not Found: /word/search/
"GET /word/search/ HTTP/1.1" 404 2835
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2832
Method Not Allowed: /words/search/
"GET /words/search/ HTTP/1.1" 405 5582
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
"GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
"GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
"POST /words/search/ HTTP/1.1" 200 5853
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5600
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 6036
"POST /words/search/ HTTP/1.1" 200 5550
"POST /words/search/ HTTP/1.1" 200 5550
"POST /words/search/ HTTP/1.1" 200 5852
"POST /words/search/ HTTP/1.1" 200 5969
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5852
"POST /words/search/ HTTP/1.1" 200 5852
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5852
"POST /words/search/ HTTP/1.1" 200 5852
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\spell_checker.py changed, reloading.
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5962
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5962
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /words/search/ HTTP/1.1" 200 5872
"POST /words/search/ HTTP/1.1" 200 7503
Watching for file changes with StatReloader
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
"GET /image HTTP/1.1" 301 0
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
Not Found: /
"GET / HTTP/1.1" 404 2930
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2981
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
Method Not Allowed (GET): /image/
"GET /image/ HTTP/1.1" 405 0
Watching for file changes with StatReloader
Method Not Allowed: /image/
"GET /image/ HTTP/1.1" 405 5709
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"OPTIONS /image/ HTTP/1.1" 200 6087
Watching for file changes with StatReloader
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 96
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 96
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5742
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5742
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5745
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5738
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5745
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5745
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5738
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5738
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"OPTIONS /image_test/ HTTP/1.1" 200 6079
"OPTIONS /image_test/ HTTP/1.1" 200 6079
"OPTIONS /image_test/ HTTP/1.1" 200 6079
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 85
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Watching for file changes with StatReloader
Method Not Allowed: /image/
"GET /image/ HTTP/1.1" 405 5709
Bad Request: /image/
"POST /image/ HTTP/1.1" 400 73
Method Not Allowed: /image/
"GET /image/ HTTP/1.1" 405 5709
Bad Request: /image/
"POST /image/ HTTP/1.1" 400 73
Method Not Allowed: /image/
"GET /image/ HTTP/1.1" 405 5709
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/?image_path=C:/Users/%E9%99%88%E4%BB%A5%E9%91%AB/Desktop/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/?image_path=C:/Users/%E9%99%88%E4%BB%A5%E9%91%AB/Desktop/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 400 96
Method Not Allowed: /words/search/
"GET /words/search/ HTTP/1.1" 405 5582
"OPTIONS /words/search/ HTTP/1.1" 200 5853
"OPTIONS /words/search/ HTTP/1.1" 200 5853
"OPTIONS /words/search/ HTTP/1.1" 200 5853
Method Not Allowed: /words/search/
"GET /words/search/ HTTP/1.1" 405 5582
- Broken pipe from ('127.0.0.1', 60168)
"POST /words/search/ HTTP/1.1" 200 7153
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3135
Bad Request: /image_test/
"POST /image_test/ HTTP/1.1" 400 5745
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 191
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Forbidden: /image_test/
"POST /image_test/ HTTP/1.1" 403 191
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
"POST /image_test/ HTTP/1.1" 500 155
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
- Broken pipe from ('127.0.0.1', 60550)
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 93463
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 93463
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 93575
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 93575
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 93575
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Internal Server Error: /image_test/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 517, in dispatch
    self.response = self.finalize_response(request, response, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 429, in finalize_response
    assert isinstance(response, HttpResponseBase), (
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Expected a `Response`, `HttpResponse` or `StreamingHttpResponse` to be returned from the view, but received a `<class 'dict'>`
"POST /image_test/ HTTP/1.1" 500 94117
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 356
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"OPTIONS /image_test/ HTTP/1.1" 200 6079
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
"POST /image_test/ HTTP/1.1" 200 521
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Watching for file changes with StatReloader
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 200 540434
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"OPTIONS /image_test/ HTTP/1.1" 200 6079
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
"POST /image_test/ HTTP/1.1" 200 521
Method Not Allowed: /image_test/
"GET /image_test/ HTTP/1.1" 405 5725
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /image_test/ HTTP/1.1" 200 521
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Not Found: /image_test/\uff1fimage_path:"D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png\u201c
"GET /image_test/%EF%BC%9Fimage_path:%22D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png%E2%80%9C HTTP/1.1" 404 3486
Not Found: /image_test/
"GET /image_test/?image_path=%22D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png%E2%80%9C HTTP/1.1" 404 227
"GET /image_test/?image_path=D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 200 521
Watching for file changes with StatReloader
"GET /image_test/?image_path=D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 200 103
"GET /image_test/?image_path=D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 200 103
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
"GET /image_test HTTP/1.1" 301 0
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
Bad Request: /image_test/
"GET /image_test/ HTTP/1.1" 400 96
"GET /image_test/?image_path=D:/software/PyCharm/PythonProject/MarkFlow/Screenshot_20250908_102429_com.huawei.hinote.png HTTP/1.1" 200 103
Not Found: /
"GET / HTTP/1.1" 404 3084
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3135
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\image_extract.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_add_views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3084
"POST /image/ HTTP/1.1" 200 103
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /word_add/
"GET /word_add/ HTTP/1.1" 405 5551
"GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 200 87533
"GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1793
"GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
"GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3796
"GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
"GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
"GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
"GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3426
"GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
"GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
"GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 200 59
"GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
"POST /word_add/ HTTP/1.1" 200 5569
Method Not Allowed: /word_add/
"GET /word_add/ HTTP/1.1" 405 5551
"POST /word_add/ HTTP/1.1" 200 5569
"POST /word_add/ HTTP/1.1" 200 5649
Watching for file changes with StatReloader
"POST /word_add/ HTTP/1.1" 200 5649
Watching for file changes with StatReloader
"POST /word_add/ HTTP/1.1" 200 5649
Watching for file changes with StatReloader
"POST /word_add/ HTTP/1.1" 200 7122
"POST /image/ HTTP/1.1" 200 103
"POST /word_add/ HTTP/1.1" 200 121
"POST /word_add/ HTTP/1.1" 200 121
"POST /word_add/ HTTP/1.1" 200 121
"POST /word_add/ HTTP/1.1" 200 121
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3236
Not Found: /
"GET / HTTP/1.1" 404 3236
"POST /image/ HTTP/1.1" 200 103
"POST /word_add/ HTTP/1.1" 200 121
"POST /word_add/ HTTP/1.1" 200 121
"POST /word_add/ HTTP/1.1" 200 121
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 3236
Not Found: /
"GET / HTTP/1.1" 404 3236
"POST /image/ HTTP/1.1" 200 103
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
"POST /word_add/ HTTP/1.1" 200 124
Watching for file changes with StatReloader
"POST /word_add/ HTTP/1.1" 200 396
"POST /word_add/ HTTP/1.1" 200 396
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /word_add/ HTTP/1.1" 200 783
"POST /image/ HTTP/1.1" 200 103
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /word_add/ HTTP/1.1" 200 413
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 296
Not Found: /words/add/
"POST /words/add/ HTTP/1.1" 404 3285
Not Found: /words/add/
"POST /words/add/ HTTP/1.1" 404 3285
Not Found: /words/add/
"POST /words/add/ HTTP/1.1" 404 3285
Not Found: /words/add/
"POST /words/add/ HTTP/1.1" 404 3285
Not Found: /words/add/
"POST /words/add/ HTTP/1.1" 404 3285
"POST /words/search/ HTTP/1.1" 200 246
"POST /words/search/ HTTP/1.1" 200 246
"POST /words/search/ HTTP/1.1" 200 296
"POST /word_add/ HTTP/1.1" 200 296
"POST /word_add/ HTTP/1.1" 200 296
"POST /words/search/ HTTP/1.1" 200 327
"POST /word_add/ HTTP/1.1" 200 327
"POST /words/search/ HTTP/1.1" 200 391
"POST /word_add/ HTTP/1.1" 200 391
"POST /word_add/ HTTP/1.1" 200 391
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\models.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3596
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 61, in post
    self.fill_cache(user_id, cache_manager)
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 87, in fill_cache
    words_to_learn = self.get_words_for_user(user_id, count)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 118, in get_words_for_user
    ).order_by('-created_at')[:count]
      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: correct_count, familiarity_level, forget_value, id, last_reviewed_at, learning_count, priority_score, user, user_id, word, word_id
"POST /word_get/ HTTP/1.1" 500 131131
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
- Broken pipe from ('127.0.0.1', 52805)
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 67, in post
    self.fill_cache(user_id, cache_manager)
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 110, in fill_cache
    words_to_learn = self.get_words_for_user(user_id, target_count)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 149, in get_words_for_user
    ).order_by('-created_at')[:count]
      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\query.py", line 1722, in order_by
    obj.query.add_ordering(*field_names)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 2291, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'created_at' into field. Choices are: correct_count, familiarity_level, forget_value, id, last_reviewed_at, learning_count, priority_score, user, user_id, word, word_id
"POST /word_get/ HTTP/1.1" 500 131951
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8237
Not Found: /word_feedback//
"GET /word_feedback// HTTP/1.1" 404 3608
Method Not Allowed: /word_feedback/
"GET /word_feedback/ HTTP/1.1" 405 5719
"POST /word_feedback/ HTTP/1.1" 200 5754
"POST /word_feedback/ HTTP/1.1" 200 5752
"POST /word_feedback/ HTTP/1.1" 200 5752
"POST /word_feedback/ HTTP/1.1" 200 5752
"POST /word_feedback/ HTTP/1.1" 200 5754
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5696
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8237
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5696
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5696
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8237
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5696
"POST /word_feedback/ HTTP/1.1" 200 5754
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8237
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5696
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8237
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 10089
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\base_vocabulary_serializer.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8344
"POST /word_feedback/ HTTP/1.1" 200 5752
"POST /word_feedback/ HTTP/1.1" 200 5752
Method Not Allowed: /word_feedback/
"GET /word_feedback/ HTTP/1.1" 405 5719
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5740
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8344
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5740
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5740
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_feedback/ HTTP/1.1" 200 5752
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5752
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 5740
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8344
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5753
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5752
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5753
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5753
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5752
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5752
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5752
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8173
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5750
"POST /word_feedback/ HTTP/1.1" 200 5753
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 279, in print_cache_words
    f"遗忘分数: {word_data['forget_level']:>2}, "
                 ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_level'
"POST /word_get/ HTTP/1.1" 500 123055
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 279, in print_cache_words
    f"遗忘分数: {word_data['forget_level']:>2}"
                 ~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_level'
"POST /word_get/ HTTP/1.1" 500 123052
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 259, in print_cache_words
    f"{word['current_correct_count']:<8} {word['learning_level']:<8} {forget_level:<8}"
                                                                      ^^^^^^^^^^^^
NameError: name 'forget_level' is not defined
"POST /word_get/ HTTP/1.1" 500 122361
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 281, in print_cache_words
    f"遗忘分数: {word_data.get['forget_level']:>2}"
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
"POST /word_get/ HTTP/1.1" 500 123525
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 261, in print_cache_words
    f"{word['current_correct_count']:<8} {word['learning_level']:<8} {word['forget_level']:<8}"
                                                                      ~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_level'
"POST /word_get/ HTTP/1.1" 500 122516
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 261, in print_cache_words
    f"{word['current_correct_count']:<8} {word['learning_level']:<8} {word['forget_level']:<8}"
                                                                      ~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_level'
"POST /word_get/ HTTP/1.1" 500 122356
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 262, in print_cache_words
    f"{word['current_correct_count']:<8} {word['learning_level']:<8} {word['forget_value']:<8}"
                                                                      ~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_value'
"POST /word_get/ HTTP/1.1" 500 122356
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
Internal Server Error: /word_get/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py", line 62, in post
    cache_manager = WordCacheManager(user_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 29, in __init__
    self.print_cache_words()
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py", line 262, in print_cache_words
    f"{word['current_correct_count']:<8} {word['learning_level']:<8} {word['forget_value']:<8}"
                                                                      ~~~~^^^^^^^^^^^^^^^^
KeyError: 'forget_value'
"POST /word_get/ HTTP/1.1" 500 122356
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 8326
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8302
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_get/ HTTP/1.1" 200 5246
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8302
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 8302
"POST /word_feedback/ HTTP/1.1" 200 5751
Watching for file changes with StatReloader
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_get/ HTTP/1.1" 200 5246
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_get/ HTTP/1.1" 200 5246
"POST /word_get/ HTTP/1.1" 200 5246
"POST /word_get/ HTTP/1.1" 200 5246
"POST /word_get/ HTTP/1.1" 200 483
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_learn_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 483
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_feedback/ HTTP/1.1" 200 5753
Watching for file changes with StatReloader
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 483
Not Found: /word_feedback/
"POST /word_feedback/ HTTP/1.1" 404 53
"POST /word_feedback/ HTTP/1.1" 200 5753
Watching for file changes with StatReloader
"POST /word_get/ HTTP/1.1" 200 483
"POST /word_feedback/ HTTP/1.1" 200 57
"POST /word_get/ HTTP/1.1" 200 572
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 461
"POST /word_feedback/ HTTP/1.1" 200 57
"POST /word_get/ HTTP/1.1" 200 636
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 584
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 596
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 497
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 483
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 572
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 461
"POST /word_feedback/ HTTP/1.1" 200 55
"POST /word_get/ HTTP/1.1" 200 636
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 584
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 596
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 497
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 573
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 462
"POST /word_feedback/ HTTP/1.1" 200 55
"POST /word_get/ HTTP/1.1" 200 585
"POST /image/ HTTP/1.1" 200 185
- Broken pipe from ('127.0.0.1', 65515)
"POST /word_get/ HTTP/1.1" 200 585
"POST /word_get/ HTTP/1.1" 200 585
"POST /word_get/ HTTP/1.1" 200 585
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 498
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 572
"POST /word_get/ HTTP/1.1" 200 572
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 462
"POST /word_feedback/ HTTP/1.1" 200 55
"POST /word_get/ HTTP/1.1" 200 585
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 498
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /word_get/
"POST /word_get/ HTTP/1.1" 400 5745
Method Not Allowed: /word_book/
"GET /word_book/ HTTP/1.1" 405 5887
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 6005
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /word_get/
"GET /word_get/ HTTP/1.1" 405 5708
"POST /word_get/ HTTP/1.1" 200 14683
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_filter_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /word_filter/
"POST /word_filter/ HTTP/1.1" 404 3778
Not Found: /word_filter/
"POST /word_filter/ HTTP/1.1" 404 3778
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 63
Watching for file changes with StatReloader
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
"POST /word_get/ HTTP/1.1" 200 14683
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
Watching for file changes with StatReloader
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 95
"POST /word_get/ HTTP/1.1" 200 14683
Method Not Allowed: /word_book/
"GET /word_book/ HTTP/1.1" 405 5880
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 5935
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Bad Request: /word_book/
"POST /word_book/ HTTP/1.1" 400 5935
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 10350
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
Not Found: /
"GET / HTTP/1.1" 404 3723
Not Found: /
"GET / HTTP/1.1" 404 3723
"POST /word_get/ HTTP/1.1" 200 498
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_get/ HTTP/1.1" 200 498
"POST /word_book/ HTTP/1.1" 200 6530
"POST /word_book/ HTTP/1.1" 200 2539
"POST /word_book/ HTTP/1.1" 200 133
"POST /word_book/ HTTP/1.1" 200 6530
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 143
"POST /word_book/ HTTP/1.1" 200 4124
"POST /word_book/ HTTP/1.1" 200 4933
"POST /word_book/ HTTP/1.1" 200 4124
"POST /word_book/ HTTP/1.1" 200 143
"POST /word_book/ HTTP/1.1" 200 4124
"POST /word_book/ HTTP/1.1" 200 143
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py", line 65, in login
    'userId': user.username  # 同时返回用户ID
              ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'username'. Did you mean: 'user_name'?
"POST /login/ HTTP/1.1" 500 108176
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py", line 65, in login
    'userId': user.username  # 同时返回用户ID
              ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'username'. Did you mean: 'user_name'?
"POST /login/ HTTP/1.1" 500 108176
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py", line 65, in login
    'userId': user.username  # 同时返回用户ID
              ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'username'. Did you mean: 'user_name'?
"POST /login/ HTTP/1.1" 500 108176
Internal Server Error: /login/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\auth_views.py", line 65, in login
    'userId': user.username  # 同时返回用户ID
              ^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'username'. Did you mean: 'user_name'?
"POST /login/ HTTP/1.1" 500 108176
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /login/ HTTP/1.1" 200 51
"POST /word_get/ HTTP/1.1" 200 498
"POST /image/ HTTP/1.1" 200 103
"POST /word_get/ HTTP/1.1" 200 498
"POST /image/ HTTP/1.1" 200 211
"POST /login/ HTTP/1.1" 200 51
"POST /image/ HTTP/1.1" 200 211
"POST /word_add/ HTTP/1.1" 200 329
"POST /word_add/ HTTP/1.1" 200 371
"POST /words/search/ HTTP/1.1" 200 401
"POST /word_add/ HTTP/1.1" 200 401
"POST /word_get/ HTTP/1.1" 200 498
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 573
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 462
"POST /word_feedback/ HTTP/1.1" 200 55
"POST /word_get/ HTTP/1.1" 200 584
"POST /word_feedback/ HTTP/1.1" 200 57
"POST /word_get/ HTTP/1.1" 200 487
"POST /word_book/ HTTP/1.1" 200 143
"POST /word_book/ HTTP/1.1" 200 3519
"POST /word_book/ HTTP/1.1" 200 7154
"POST /word_book/ HTTP/1.1" 200 3519
"POST /word_book/ HTTP/1.1" 200 143
"POST /word_book/ HTTP/1.1" 200 3519
"POST /word_book/ HTTP/1.1" 200 143
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /word_get/ HTTP/1.1" 200 487
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 531
"POST /word_get/ HTTP/1.1" 200 531
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 534
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 516
Not Found: /theme/default/assets/umi.js
"GET /theme/default/assets/umi.js HTTP/1.1" 404 3822
Not Found: /theme/default/assets/umi.js
"GET /theme/default/assets/umi.js HTTP/1.1" 404 3822
Not Found: /user/umi.min.js
"GET /user/umi.min.js HTTP/1.1" 404 3786
Not Found: /user/umi.min.js
"GET /user/umi.min.js HTTP/1.1" 404 3786
Not Found: /
"GET / HTTP/1.1" 404 3723
Not Found: /
"GET / HTTP/1.1" 404 3723
Not Found: /
"GET / HTTP/1.1" 404 3723
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 6395
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\word_filter_views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 11587
"POST /word_book/ HTTP/1.1" 200 20752
"POST /word_book/ HTTP/1.1" 200 6399
"POST /word_book/ HTTP/1.1" 200 25932
"POST /login/ HTTP/1.1" 200 51
"POST /word_book/ HTTP/1.1" 200 10805
"POST /word_book/ HTTP/1.1" 200 10805
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 10805
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 11587
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 3020
"POST /word_book/ HTTP/1.1" 200 7925
"POST /word_book/ HTTP/1.1" 200 10805
"POST /word_book/ HTTP/1.1" 200 141
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 11832
Watching for file changes with StatReloader
"POST /word_book/ HTTP/1.1" 200 11832
"POST /word_book/ HTTP/1.1" 200 21440
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /basic_message/
"GET /basic_message/ HTTP/1.1" 405 5777
Internal Server Error: /basic_message/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\basic_massage.py", line 87, in post
    ) if F('learning_count') > 0 else None
         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'F' and 'int'
"POST /basic_message/ HTTP/1.1" 500 107364
"POST /login/ HTTP/1.1" 200 51
"POST /login/ HTTP/1.1" 200 51
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 11205
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Method Not Allowed: /basic_message/
"GET /basic_message/ HTTP/1.1" 405 5777
Internal Server Error: /basic_message/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\basic_massage.py", line 87, in post
    correct_rate=Case(
                 ^^^^^
TypeError: TokenList.__init__() got an unexpected keyword argument 'default'
"POST /basic_message/ HTTP/1.1" 500 107331
"POST /login/ HTTP/1.1" 200 51
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
Watching for file changes with StatReloader
Method Not Allowed: /basic_message/
"GET /basic_message/ HTTP/1.1" 405 5777
Internal Server Error: /basic_message/
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\views\generic\base.py", line 105, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\views\basic_massage.py", line 95, in post
    When(then=Value(None)),  # 最后一个When不写条件，作为默认值
    ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\django\db\models\expressions.py", line 1569, in __init__
    raise TypeError(
TypeError: When() supports a Q object, a boolean expression, or lookups as a condition.
"POST /basic_message/ HTTP/1.1" 500 112105
"POST /word_get/ HTTP/1.1" 200 516
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
Method Not Allowed: /basic_message/
"GET /basic_message/ HTTP/1.1" 405 5756
"POST /word_book/ HTTP/1.1" 200 3125
"POST /basic_message/ HTTP/1.1" 200 6017
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 11205
"POST /login/ HTTP/1.1" 200 51
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Signal handler <promise@0x224812c89b0 --> <bound method Celery._autodiscover_tasks of <Celery MarkFlow at 0x224812cd340>>> raised: TypeError("shared_task() got an unexpected keyword argument 'bind'")
Traceback (most recent call last):
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\utils\dispatch\signal.py", line 280, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\vine\promises.py", line 161, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\vine\promises.py", line 158, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\app\base.py", line 788, in _autodiscover_tasks
    return self._autodiscover_tasks_from_fixups(related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\app\base.py", line 797, in _autodiscover_tasks_from_fixups
    return self._autodiscover_tasks_from_names([
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\app\base.py", line 792, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\loaders\base.py", line 220, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\loaders\base.py", line 246, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\PyCharm\PythonProject\MarkFlow\.venv\Lib\site-packages\celery\loaders\base.py", line 270, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2800.0_x64__qbz5n2kfra8p0\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\tasks.py", line 18, in <module>
    @shared_task(bind=True, retry_backoff=3, retry_kwargs={'max_retries': 3})
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: shared_task() got an unexpected keyword argument 'bind'
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /basic_message/ HTTP/1.1" 200 159
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 11205
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 141
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8220
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlowImpl\utils\word_cache_manager.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\software\PyCharm\PythonProject\MarkFlow\MarkFlow\settings.py changed, reloading.
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /basic_message/ HTTP/1.1" 200 159
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /basic_message/ HTTP/1.1" 200 159
"POST /image/ HTTP/1.1" 200 211
"POST /word_add/ HTTP/1.1" 200 357
"POST /words/search/ HTTP/1.1" 200 458
"POST /word_add/ HTTP/1.1" 200 458
"POST /word_get/ HTTP/1.1" 200 516
"POST /word_feedback/ HTTP/1.1" 200 54
"POST /word_get/ HTTP/1.1" 200 520
"POST /word_book/ HTTP/1.1" 200 12421
"POST /word_book/ HTTP/1.1" 200 12421
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8898
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8898
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 12421
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8898
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 678
"POST /image/ HTTP/1.1" 200 157
"POST /login/ HTTP/1.1" 200 51
"POST /basic_message/ HTTP/1.1" 200 159
"POST /word_book/ HTTP/1.1" 200 12421
"POST /word_book/ HTTP/1.1" 200 12421
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 8898
"POST /word_book/ HTTP/1.1" 200 678
"POST /image/ HTTP/1.1" 200 185
"POST /word_add/ HTTP/1.1" 200 2955
"POST /image/ HTTP/1.1" 200 150
"POST /word_add/ HTTP/1.1" 200 2005
"POST /word_get/ HTTP/1.1" 200 520
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 12407
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_get/ HTTP/1.1" 200 520
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 12407
"POST /word_get/ HTTP/1.1" 200 520
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 15930
"POST /word_book/ HTTP/1.1" 200 3125
"POST /word_book/ HTTP/1.1" 200 12407
"POST /word_book/ HTTP/1.1" 200 678
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"POST /login/ HTTP/1.1" 200 51
"POST /login/ HTTP/1.1" 200 51
"POST /basic_message/ HTTP/1.1" 200 159
"POST /image/ HTTP/1.1" 200 185
"POST /word_add/ HTTP/1.1" 200 389
"POST /word_add/ HTTP/1.1" 200 2955
"POST /words/search/ HTTP/1.1" 200 458
"POST /word_add/ HTTP/1.1" 200 458
"POST /word_get/ HTTP/1.1" 200 520
"POST /word_feedback/ HTTP/1.1" 200 56
"POST /word_get/ HTTP/1.1" 200 529
"POST /word_book/ HTTP/1.1" 200 16626
"POST /word_book/ HTTP/1.1" 200 16626
"POST /word_book/ HTTP/1.1" 200 3686
"POST /word_book/ HTTP/1.1" 200 12542
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 3686
"POST /word_book/ HTTP/1.1" 200 12542
"POST /word_get/ HTTP/1.1" 200 529
"POST /word_book/ HTTP/1.1" 200 16626
"POST /word_book/ HTTP/1.1" 200 16626
"POST /word_book/ HTTP/1.1" 200 3686
"POST /word_book/ HTTP/1.1" 200 12542
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 678
"POST /word_book/ HTTP/1.1" 200 3686
- Broken pipe from ('127.0.0.1', 61615)
